spring:
  datasource:
    url: jdbc:postgresql://postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: IVKCZXQfYWutRTytakhnBJokeqSMOqfN

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: todo-list

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 900000
      refresh-token:
        expiration: 86400000

X-Super-Admin-Secret-Key: superman admin turing machine gigachad sigma
X-Admin-Secret-Key: admin turing machine alpha beta

server:
  port: 8088

bezkoder:
  openapi:
    dev-url: http://localhost:8088
    prod-url: https://localhost:8080

logging:
  level:
    org:
    springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      hibernate: DEBUG
      jpa: DEBUG
      sql: DEBUG
      jwt: DEBUG
      bezkoder: DEBUG